### ISSUE TITLE
Use copies of global test objects

### ISSUE THREAD

**Issue by artek-koltun** [opiproject/opi-spdk-bridge#443]
Global test objects like [here](https://github.com/opiproject/opi-spdk-bridge/blob/9cae97bde7574edc6d56b0d6d057bdb786882b97/pkg/middleend/qos_test.go#L25) are widely used across the test code
```Go
	testQosVolume     = &pb.QosVolume{
		VolumeId: &_go.ObjectKey{Value: "volume-42"},
		MaxLimit: &pb.QosLimit{RwBandwidthMbs: 1},
	}
```
They are used as an object in a request, as an already existing object in db or to provide some common field to another structure.

During the test, the test object can be changed by the server internally, potentially affecting all subsequent tests, decreasing the test set fidelity and potentially leading to flaky tests. Unfortunately, Go does not provide an ability to create const structs.

There are a couple of ways how this can be overcome in the bridge code.

1. We can use `server.ProtoClone` to copy required objects. Like
```Go
// beginning of a test
tt.in = server.ProtoClone(tt.in)
tt.out = server.ProtoClone(tt.out)
tt.existingVolume = server.ProtoClone(tt.existingVolume)
// or `server.ProtoClone` can be used in a test table at a test case definition.
```
Probably, creation of clone objects is needed only if a resource is set for internal structures, like adding an entry to the db.

2. Create a function which creates test objects like
```Go
func testQosVolume() *pb.QosVolume
	return &pb.QosVolume{
		VolumeId: &_go.ObjectKey{Value: "volume-42"},
		MaxLimit: &pb.QosLimit{RwBandwidthMbs: 1},
	}
```
Thus, `testQosVolume()` creates a new copy on every usage and the original object cannot be modified.

3. Use public API to create resource. For example, if a resource must exist, run Create call beforehand, It can complicate the test environment, since we need to provide all underlying SPDK stub calls.

4. Replace all test objects in place, but it can incur too much duplication

**Comment by artek-koltun** [comment]
Apparently, we changed a global test variable field there, thus test sis not fail...
https://github.com/opiproject/opi-spdk-bridge/pull/579#discussion_r1290014471

**Comment by intelfisz** [comment]
I like approach no. 2 best - it is a factory pattern and seems very suitable for the problem at hand.

**Comment by artek-koltun** [comment]
resolved in https://github.com/opiproject/opi-spdk-bridge/pull/591
