### ISSUE TITLE
[backend][nvme] bdev_nvme_attach_controller: test local NVMe

### ISSUE THREAD

**Issue by glimchb** [opiproject/opi-spdk-bridge#560]
today we using remote nvme over fabrics
we should support local nvme as well
it should work, just needs testing and small fixes

see https://spdk.io/doc/jsonrpc.html#rpc_bdev_nvme_attach_controller

Example request:
```
{
  "params": {
    "trtype": "pcie",
    "name": "Nvme0",
    "traddr": "0000:0a:00.0"
  },
  "jsonrpc": "2.0",
  "method": "bdev_nvme_attach_controller",
  "id": 1
}
```
Example response:
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": [
    "Nvme0n1"
  ]
}
```

**Comment by glimchb** [comment]
@artek-koltun I think you tested this, if works and documented enough, please close this issue

**Comment by artek-koltun** [comment]
I will recheck and adjust the code/close the issue

**Comment by artek-koltun** [comment]
Tested that it is possible to attach a local pcie drive
