### ISSUE TITLE
keep opi-api version in built image's label

### ISSUE THREAD

**Issue by yanjing1104** [opiproject/opi-spdk-bridge#576]

**Comment by glimchb** [comment]
you mean in docker file ?

**Comment by yanjing1104** [comment]
> you mean in docker file ?

Yes

**Comment by glimchb** [comment]
can you propose PR?

**Comment by yanjing1104** [comment]
> can you propose PR?

Yes, I will try to propose one.

**Comment by yanjing1104** [comment]
> can you propose PR?

https://github.com/opiproject/opi-spdk-bridge/pull/590 Could you help to review?
