### ISSUE TITLE
Resource names should not contain service names

### ISSUE THREAD

**Issue by artek-koltun** [opiproject/opi-spdk-bridge#642]
Resource names should not contain service names
https://google.aip.dev/122#fields-representing-resource-names

**Comment by glimchb** [comment]
do you refer to this note under  https://google.aip.dev/122#full-resource-names 
```
Note: The full resource name should not be used for cross-API references where the owning API is clear; it is only used if a field refers to resources in multiple APIs where ambiguity is possible.
```
?

**Comment by artek-koltun** [comment]
yes

**Comment by artek-koltun** [comment]
resolved in https://github.com/opiproject/opi-spdk-bridge/pull/879
